apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: ci
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: xxx.cn-beijing.nas.aliyuncs.com
