apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulset-multi-replica-pvc
  labels:
    app: nginx-statefulset-multi-replica-pvc
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-statefulset-multi-replica-pvc
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: nginx-statefulset-multi-replica-pvc
spec:
  selector:
    matchLabels:
      app: nginx-statefulset-multi-replica-pvc
  serviceName: "nginx-statefulset-multi-replica-pvc"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-statefulset-multi-replica-pvc
    spec:
      containers:
      - name: nginx-statefulset-multi-replica-pvc
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: disk-ssd
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: disk-ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "alicloud-disk-ssd"
      resources:
        requests:
          storage: 20Gi