kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-ssd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-ssd
  resources:
    requests:
      storage: 20Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-volume-ondemand
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-flexvolume-disk
        image: nginx
        volumeMounts:
          - name: "disk-pvc"
            mountPath: "/data"
      restartPolicy: "Always"
      volumes:
        - name: "disk-pvc"
          persistentVolumeClaim:
            claimName: disk-ssd
