apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: default
  labels:
    name: tomcat
spec:
  containers:
  - image: tomcat
    name: tomcat-test
    volumeMounts:
    - mountPath: /usr/local/tomcat/logs
      name: accesslogs
    env:
     - name: aliyun_logs_catalina                                 
       value: "stdout"                                             ##采集标准输出日志
     - name: aliyun_logs_access
       value: "/usr/local/tomcat/logs/catalina.*.log"              ## 采集容器内日志文件 
  volumes:
    - name: accesslogs
      emptyDir: {}