apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ipv6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ipv6
  template:
    metadata:
      labels:
        app: nginx-ipv6
    spec:
      containers:
      - name: nginx-ipv6
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-ip-version: ipv6
  name: nginx-ipv6-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ipv6
  type: LoadBalancer